import {chromium} from 'playwright';
import {readFileSync,writeFileSync,readdirSync,existsSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {createServer} from 'node:http';
import assert from 'node:assert/strict';
const root=resolve('.');
const server=createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const file=resolve(root,'.'+p);if(!file.startsWith(root+'/')||!existsSync(file)){res.writeHead(404);return res.end('not found');}const ext=file.split('.').pop();res.setHeader('Content-Type',({html:'text/html; charset=utf-8',css:'text/css',js:'application/javascript',svg:'image/svg+xml',json:'application/json',zip:'application/zip'})[ext]||'text/plain');res.end(readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const localChromium='/home/nmaldaner/.cache/ms-playwright/chromium-1234/chrome-linux/chrome';
const executablePath=process.env.CHROMIUM_PATH||(existsSync(localChromium)?localChromium:undefined);
const browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});
const results=[];const errors=[];
const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
function record(name,value){results.push({name,passed:!!value});if(!value)throw Error(name);}
try{
const paths=['index.html',...Array.from({length:4},(_,i)=>`curso/trilha${i+1}/index.html`),...Array.from({length:4},(_,i)=>[1,2].map(j=>`curso/trilha${i+1}/modulo-${i+1}-${j}.html`)).flat()];
let links=0,svgs=0,topics=0;
for(const file of paths){await p.goto(base+'/'+file);await p.waitForFunction(()=>window.INEMA);const report=await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return {duplicate:ids.filter((v,i)=>ids.indexOf(v)!==i),links:[...document.querySelectorAll('a[href],script[src],link[href]')].map(a=>a.getAttribute('href')||a.getAttribute('src')),svgs:document.querySelectorAll('svg[role=img]').length,topics:document.querySelectorAll('[data-inema-topic]').length,total:INEMA.progress('curso').total,overflow:document.documentElement.scrollWidth>innerWidth+1};});assert.equal(report.total,48);assert.deepEqual(report.duplicate,[]);assert.equal(report.overflow,false,`${file} desktop overflow`);svgs+=report.svgs;topics+=report.topics;
for(const link of report.links){if(/^(https?:|data:|mailto:)/.test(link))continue;const [path,hash]=link.split('#');const dest=resolve(dirname(resolve(root,file)),path||'.');const actual=path?dest:resolve(root,file);if(path)assert.ok(existsSync(actual),`${file} broken link ${link}`);if(hash&&(!path||path.endsWith('.html'))){const html=readFileSync(actual,'utf8');assert.ok(html.includes(`id="${hash}"`),`missing anchor ${file} ${link}`);}links++;}
}
record('13 páginas; links locais, IDs, manifesto e desktop',true);record('53 SVG e 48 tópicos',svgs===53&&topics===48);
await p.goto(base+'/index.html');await p.locator('#theme-toggle').click();record('Toggle claro pela interface',await p.evaluate(()=>!document.documentElement.classList.contains('dark')));await p.locator('#theme-toggle').click();await p.screenshot({path:'verificacao/inicio-desktop.png'});
await p.goto(base+'/curso/trilha1/index.html');await p.locator('.topic-toggle').first().click();record('Accordion abre',await p.locator('.topic-toggle').first().getAttribute('aria-expanded')==='true');await p.locator('.topic-toggle').nth(1).click();record('Accordion fecha anterior',await p.locator('.topic-toggle').first().getAttribute('aria-expanded')==='false');await p.locator('[data-open-modal]').first().click();record('Modal carrega iframe',await p.locator('dialog').evaluate(x=>x.open)&&await p.locator('iframe').getAttribute('src')==='modulo-1-1.html');await p.locator('[data-close-modal]').click();
await p.goto(base+'/curso/trilha1/modulo-1-1.html');await p.locator('[data-inema-read-toggle]').first().click();await p.reload();record('Leitura persiste',await p.locator('[data-inema-read-toggle]').first().getAttribute('aria-pressed')==='true');record('Progresso do curso agrega',await p.evaluate(()=>INEMA.progress('curso').done)===1);
await p.locator('[data-inema-doubt-toggle]').first().click();await p.locator('[data-inema-journey-open]').click();record('Jornada tem diálogo',await p.locator('[role=dialog][aria-modal=true]').count()===1);await p.keyboard.press('Escape');
await p.locator('[data-inema-check-option="1"]').click();record('Quiz aceita resposta correta',(await p.locator('[data-inema-check-feedback]').innerText()).startsWith('Correto.'));
await p.evaluate(()=>{const p=document.querySelector('[data-inema-block]');const r=document.createRange();r.setStart(p.firstChild,0);r.setEnd(p.firstChild,35);INEMA.highlight(r,{color:'yellow',note:'Minha nota de teste'});});record('Highlight com nota',await p.locator('mark.inema-hl').count()>0);await p.reload();record('Highlight restaurado',await p.locator('mark.inema-hl').count()>0);
await p.locator('[data-inema-appearance-toggle]').click();await p.locator('[data-inema-set-theme=sepia]').click();record('Aparência pela interface',await p.evaluate(()=>document.documentElement.dataset.theme==='sepia'));await p.keyboard.press('Escape');await p.evaluate(()=>INEMA.setPref('theme','inema-dark'));const state=await p.evaluate(()=>INEMA.exportJSON());record('JSON válido',JSON.parse(state).courseId==='agent-skills-codex');record('Import inválido no-op',await p.evaluate(()=>{const before=INEMA.exportJSON();const r=INEMA.importJSON('{bad');return !r.ok&&JSON.parse(before).read['modulo-1-1#topico-1']===JSON.parse(INEMA.exportJSON()).read['modulo-1-1#topico-1'];}));
record('Round-trip com campos futuros',await p.evaluate(()=>{let x=JSON.parse(INEMA.exportJSON());x.futureField={hello:'preservar'};const r=INEMA.importJSON(JSON.stringify(x));return r.ok&&JSON.parse(INEMA.exportJSON()).futureField?.hello==='preservar';}));
record('Import estruturalmente inválido no-op',await p.evaluate(()=>{const before=INEMA.exportJSON();const r=INEMA.importJSON(JSON.stringify({schemaVersion:1,courseId:'agent-skills-codex',notes:{x:'bad'}}));return !r.ok&&JSON.parse(before).read['modulo-1-1#topico-1']===JSON.parse(INEMA.exportJSON()).read['modulo-1-1#topico-1'];}));
await p.locator('#topico-3').evaluate(el=>el.scrollIntoView({behavior:'instant'}));await p.waitForTimeout(600);await p.goto(base+'/index.html');await p.locator('[data-course-resume]').click();await p.waitForTimeout(300);record('Retomada entre páginas por âncora',p.url().includes('modulo-1-1.html#topico-3'));
await p.goto(base+'/curso/trilha2/modulo-2-2.html');await p.screenshot({path:'verificacao/modulo-desktop.png'});
const contrast=[];for(const theme of ['inema-dark','claro','sepia','foco','contraste']){await p.evaluate(theme=>INEMA.setPref('theme',theme),theme);const vals=await p.evaluate(()=>{function color(token){const d=document.createElement('span');d.style.color=`var(${token})`;document.body.append(d);const c=getComputedStyle(d).color;d.remove();return c;}return {bg:color('--bg'),text:color('--text'),muted:color('--text-muted')};});function lum(s){let v=s.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2];}const bg=lum(vals.bg);for(const key of ['text','muted']){let t=lum(vals[key]);let ratio=(Math.max(bg,t)+.05)/(Math.min(bg,t)+.05);assert.ok(ratio>=4.5,`${theme} ${key} ${ratio}`);contrast.push({theme,key,ratio});}}
record('Contraste de texto nos cinco temas ≥ 4,5',true);
await p.evaluate(()=>INEMA.setPref('theme','claro'));await p.screenshot({path:'verificacao/modulo-claro.png'});await p.evaluate(()=>INEMA.setPref('theme','inema-dark'));
await p.setViewportSize({width:390,height:844});for(const file of paths){await p.goto(base+'/'+file);record('Mobile sem overflow: '+file,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await p.goto(base+'/index.html');await p.locator('#theme-toggle').click();record('Toggle claro pela interface',await p.evaluate(()=>!document.documentElement.classList.contains('dark')));await p.locator('#theme-toggle').click();await p.screenshot({path:'verificacao/inicio-mobile.png',fullPage:true});await p.goto(base+'/curso/trilha2/modulo-2-2.html');await p.screenshot({path:'verificacao/modulo-mobile.png'});await p.locator('#topico-1').evaluate(x=>x.scrollIntoView({behavior:'instant'}));await p.screenshot({path:'verificacao/diagrama-mobile.png'});
await p.goto(base+'/curso/trilha4/modulo-4-1.html');await p.locator('#accepted').fill('0');record('Simulador trata zero', (await p.locator('#effective').innerText()).includes('indefinido'));
const nojs=await browser.newContext({javaScriptEnabled:false});const np=await nojs.newPage();await np.goto(base+'/curso/trilha1/index.html');record('Leitura sem JS',await np.locator('.topic-explanation').first().isVisible());await nojs.close();
const nostore=await browser.newContext();await nostore.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}});});const sp=await nostore.newPage();await sp.goto(base+'/curso/trilha1/modulo-1-1.html');await sp.locator('[data-inema-read-toggle]').first().click();record('Storage bloqueado mantém leitura e estado em memória',await sp.locator('[data-inema-read-toggle]').first().getAttribute('aria-pressed')==='true');await nostore.close();
const fp=await ctx.newPage();await fp.goto('file://'+root+'/curso/trilha1/modulo-1-1.html');record('Curso abre em file://',await fp.locator('[data-inema-topic]').count()===6&&await fp.evaluate(()=>!!window.INEMA));await fp.close();record('Sem exceções JavaScript',errors.length===0);
writeFileSync('verificacao/resultados.json',JSON.stringify({results,links,svgs,topics,contrast,errors},null,2));console.log(JSON.stringify({passed:results.length,links,svgs,topics,errors},null,2));
}catch(e){writeFileSync('verificacao/falha-testes.json',JSON.stringify({error:e.message,results,errors},null,2));console.error(e);process.exitCode=1;}finally{await browser.close();server.close();}
